### ISSUE TITLE
atom-ide support

### ISSUE THREAD

**Issue by Ikuyadeu** [REditorSupport/atom-language-r-legacy#1]
[atom-ide](https://atom.io/ide) was released.
This is use language server, and it is useful for test our language server.
Should this repository support this, or create new repository like https://github.com/atom/ide-java/?

**Comment by randy3k** [comment]
may be we should create `atom-ide-r` and this repo keeps the R syntax file?

**Comment by Ikuyadeu** [comment]
Yes, I think so this repo need R syntax file.
But almost atom-ide-xxx does't have syntax file.

**Comment by randy3k** [comment]
I will wait for atom users' responses

@kylebarron @guillaumechaumet

**Comment by kylebarron** [comment]
All the other languages currently supported with `atom-ide` have separate repositories for the language package. I don't believe there's anything stopping you from putting the code for `atom-ide-r` in this repository (the syntax highlighting files go in the `grammars/` top-level folder and the other code would go in `lib/`), but there could be some users who want the syntax highlighting without using the other IDE features.

**Comment by randy3k** [comment]
[atom-ide-r](https://github.com/REditorSupport/atom-ide-r) is out.
